civic_map/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls')),
    url(r'^', include(
        'locations.urls',
        namespace='locations'
    )),
]

locations/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'new$', views.new, name='new'),
    url(r'(?P<id>[0-9]+)/$', views.view, name='view'),
    url(r'(?P<id>[0-9]+)/edit$', views.edit, name='edit'),
    url(r'(?P<id>[0-9]+)/review$', views.review, name='review'),
    url(r'$', views.index, name='index'),
]

user/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'', include('django.contrib.auth.urls')),
    url(r'register/$', views.register, name='register'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # url(r'login/$', auth_views.login),
    # url(r'logout/$', auth_views.logout),
    # url(r'password_change/$', auth_views.password_change),
    # url(r'password_change/done/$', auth_views.password_change_done),
    #url(r'password_reset/$', views.do_password_reset, name='password_reset'),
    #url(r'password_reset/done/$', views.password_reset_done, name='password_reset_done'),

    # url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm),
    # url(r'reset/done/$', auth_views.password_reset_complete),
]

templates/partials/header.html
{% load i18n %}

<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="sr-only">
                    Toggle navigation
                </span>
                <span class="icon-bar">
                </span>
                <span class="icon-bar">
                </span>
                <span class="icon-bar">
                </span>
            </button>
            <a class="navbar-brand" href="/">
                Civic Map
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="{% url 'locations:new' %}">Add location</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">
                        <i class="icon-key"></i> {% trans 'Logout' %} </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                <li>
                    <a href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>