civic_map/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls')),
    url(r'^', include(
        'locations.urls',
        namespace='locations'
    )),
]

locations/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'new$', views.new, name='new'),
    url(r'(?P<id>[0-9]+)/$', views.view, name='view'),
    url(r'(?P<id>[0-9]+)/edit$', views.edit, name='edit'),
    url(r'(?P<id>[0-9]+)/review$', views.review, name='review'),
    url(r'$', views.index, name='index'),
]

user/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'', include('django.contrib.auth.urls')),
    url(r'register/$', views.register, name='register'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    # url(r'login/$', auth_views.login),
    # url(r'logout/$', auth_views.logout),
    # url(r'password_change/$', auth_views.password_change),
    # url(r'password_change/done/$', auth_views.password_change_done),
    #url(r'password_reset/$', views.do_password_reset, name='password_reset'),
    #url(r'password_reset/done/$', views.password_reset_done, name='password_reset_done'),

    # url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm),
    # url(r'reset/done/$', auth_views.password_reset_complete),
]

locations/models.py
from django.db import models
from django.urls import reverse
from simple_history.models import HistoricalRecords
from civic_map import settings


class Location(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=10240)
    latitude = models.DecimalField(max_digits=20, decimal_places=18)
    longitude = models.DecimalField(max_digits=20, decimal_places=18)
    program = models.CharField(max_length=255)
    contact_info = models.CharField(max_length=255)
    tags = models.ManyToManyField('Tag', blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    _credibility = models.DecimalField(
        max_digits=5,
        decimal_places=4,
        default=0.0,
        db_column='credibility'
    )

    @property
    def credibility(self):
        return min(1, max(self._credibility, 0))

    @credibility.setter
    def credibility(self, value):
        self._credibility = min(1, max(value, 0))


    # putem folosi un ImageField pentru o poza cu locatia
    # https://docs.djangoproject.com/en/1.10/ref/models/fields/#imagefield

    history = HistoricalRecords()

    @property
    def _history_user(self):
        return self.user

    @_history_user.setter
    def _history_user(self, value):
        self.user = value

    def get_absolute_url(self):
        return reverse('locations:view', args=[self.id])

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']


class Tag(models.Model):
    name = models.CharField(max_length=255)


class Review(models.Model):
    MARK_1 = 1
    MARK_2 = 2
    MARK_3 = 3
    MARK_4 = 4
    MARK_5 = 5
    MARK_CHOICES = (
        (MARK_1, 'Mark 1'),
        (MARK_2, 'Mark 2'),
        (MARK_3, 'Mark 3'),
        (MARK_4, 'Mark 4'),
        (MARK_5, 'Mark 5'),
    )

    content = models.TextField(max_length=65535, blank=True, null=True)
    mark = models.PositiveSmallIntegerField(
        choices=MARK_CHOICES,
        default=MARK_5,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    location = models.ForeignKey(
        'Location',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ['-id']

    # pentru unique ar trebui folosit ceva gen
    # https://stackoverflow.com/questions/2270808/compound-composite-primary-unique-key-with-django
    # doar ca am impresia ca elimina primary key-ul
    # asa ca sau trebuie declarat id ca primary key separat
    # sau putem folosi alea ca primary key si vedem cum se comporta
    # need testing

locations/forms.py
from django import forms
from .models import Location, Review

from easy_maps.widgets import MapWidget


class LocationForm(forms.ModelForm):
    address = forms.CharField(
        widget=MapWidget({
            'class': 'vTextField',
            'size': 60,
            'hidden': True,
        }),
        initial='Bucharest, Romania',
    )

    def __init__(self, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)

        instance = kwargs.get('instance', None)
        if instance is not None:
            self.fields['address'].initial = \
                '%.16f, %.16f' % (instance.latitude, instance.longitude)

    class Meta:
        model = Location
        exclude = ('user', 'tags', '_credibility')
        widgets = {
            'latitude': forms.NumberInput({'size': 34}),
            'longitude': forms.NumberInput({'size': 34}),
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user', 'location')

locations/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404
)
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from functools import reduce

from .models import Location
from civic_map import settings
from .forms import LocationForm, ReviewForm

from decimal import *

import operator

def index(request):
    query = request.GET.get('q')
    if query:
        query_list = query.split()
        locations = Location.objects.filter(
            reduce(operator.and_,
                   (Q(name__icontains=q) for q in query_list)) |
            reduce(operator.and_,
                   (Q(description__icontains=q) for q in query_list))
        )
    else:
        locations = Location.objects.all()

    paginator = Paginator(locations, 50)

    page = request.GET.get('page', default=1)
    try:
        locations = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        locations = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        locations = paginator.page(paginator.num_pages)

    if len(locations) == 0:
        lat, lng = settings.EASY_MAPS_CENTER
    else:
        lat = sum(l.latitude for l in locations) / len(locations)
        lng = sum(l.longitude for l in locations) / len(locations)

    map_center = {
        'latitude': lat,
        'longitude': lng,
    }

    context = {
        'locations': locations,
        'map_center': map_center,
        'query': query
    }

    return render(request, 'locations/index.html', context)


def view(request, id):
    location = get_object_or_404(Location, id=id)
    context = {
        'location': location,
        'reviews': location.review_set.all(),
    }

    return render(request, 'locations/view.html', context)


@login_required
def review(request, id):
    location = get_object_or_404(Location, id=id)

    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.location = location
            review.save()

            location.credibility += Decimal(0.25);
            location.save();

            return redirect('locations:view', id=location.id)
    else:
        review_form = ReviewForm()

    context = {
        'location': location,
        'review_form': review_form,
    }

    return render(request, 'locations/review.html', context)


@login_required
def edit(request, id):
    location = get_object_or_404(Location, id=id)
    if request.method == 'POST':
        form = LocationForm(request.POST, instance=location)
        if form.is_valid():
            location = form.save(commit=False)
            location.user = request.user
            location.save()

            return redirect('locations:view', id=location.id)
    else:
        form = LocationForm(instance=location)

    context = {'form': form}

    return render(request, 'locations/edit.html', context)


@login_required
def new(request):
    if request.method == 'POST':
        form = LocationForm(request.POST)

        if form.is_valid():
            location = form.save(commit=False)
            location.user = request.user
            location.save()

            return redirect('locations:view', id=location.id)
    else:
        form = LocationForm()

    context = {'form': form}

    return render(request, 'locations/edit.html', context)

templates/locations/edit.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <div id="addLocationBlock" class="login-panel panel panel-default">
            <div class="panel-heading">
                 <h3 class="panel-title">
                    {% if form.instance and form.instance.id %}
                        Edit location -
                        <a href="{{ form.instance.get_absolute_url }}">
                            {{ form.instance.name }}</a>
                    {% else %}
                        Add location
                    {% endif %}
                </h3>
            </div>
            <div class="panel-body">
                <form method="POST">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="field-wrapper">
                            {{ field.errors }}
                            {{ field.label_tag }} {{ field }}
                        </div>
                    {% endfor %}

                    <input id="submit_btn" class="btn btn-lg btn-success" type="submit" value="{% trans "Submit" %}">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
<script>
// Adds a marker to the map.
var addMarker = function(location, map) {
    // Add the marker at the clicked location, and add the next-available label
    // from the array of alphabetical characters.
    var marker = new google.maps.Marker({
        position: location,
        map: map
    });

    if (window.markers && window.markers.length > 0) {
        var old_marker = window.markers.shift();
        old_marker.setMap(null);
    }

    window.markers.push(marker);
}

google.maps.event.addDomListener(window, 'load', function() {
    google.maps.event.addListener(window.map, 'click', function(event) {
        addMarker(event.latLng, window.map);
        $('#id_latitude').val(event.latLng.lat());
        $('#id_longitude').val(event.latLng.lng());
    });
    window.mapElem.style.width = '100%';
});
</script>
{% endblock %}

templates/locations/index.html
{% extends "base.html" %}
{% load i18n %}
{% load map_tags %}
{% load url_replace %}

{% block content %}
<div class="row-fluid">
    <div class="col-xs-12 col-md-9 col-lg-9">
        <div>
            {% map map_center.latitude map_center.longitude False 600 500 14 %}
        </div>

        <div id="locationInfo" class="panel panel-default panel-collapse collapse" style="overflow:hidden">
            <div class="panel-heading">
                <h2 id="hName"></h2>
            </div>
            <div class="panel-body">
                <ul>
                    <li>
                        <b>Description: </b>
                        <p id="pDescription"></p>
                    </li>
                    <li>
                        <b>Program: </b>
                        <p id="pProgram"></p>
                    </li>
                    <li>
                        <b>Contact: </b>
                        <p id="pContact"></p>
                    </li>
                </ul>
                <a id="aReviews" href="">View reviews</a>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-md-3 col-lg-3" style="margin-bottom: 20px">
        <form class="form" method="GET">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search" name="q"
                   {% if query %}
                   value="{{ query }}"
                   {% endif %}>
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </form>

        {% if query %}
            <p>Showing search results for: '{{ query }}'</p>
        {% endif %}
    </div>

    {% for location in locations %}
    <div class="col-xs-6 col-md-3 col-lg-3">
        <div class="panel panel-default locations-item">
            <div class="panel-heading">
                <a href="{{ location.get_absolute_url }}"
                    title="{{ location.name }}"
                    class="locations-item__title">
                    {{ location.name|title }}
                </a>
            </div>
            {% if location.description %}
            <div class="panel-body">
                <p class="locations-item__description">
                    {{ location.description|truncatewords:10 }}
                </p>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}

    {% if locations.paginator.num_pages > 1 %}
    <div class="pagination col-xs-12 col-md-12 col-lg-12" style="text-align: center">
        <span class="step-links">
            {% if locations.has_previous %}
                <a
                href="?{% url_replace page=locations.previous_page_number %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ locations.number }} of {{ locations.paginator.num_pages }}.
            </span>

            {% if locations.has_next %}
                <a href="?{% url_replace page=locations.next_page_number %}">next</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block extrajs %}
<script>
    var getOpacityForCredibility = function(cred) {
        var minCred = 0.0; // MAGIC
        var maxCred = 1.0; // MAGIC
        var minOpac = 0.4; // A KIND OF MAGIC
        var maxOpac = 1.0; // MAGIC NUMEROS

        cred = Math.max(minCred, cred);
        cred = Math.min(maxCred, cred);

        var ratio = (cred - minCred) / (maxCred - minCred);
        var opac = minOpac + (maxOpac - minOpac) * ratio;

        return opac;
    }

    var locations = [];
    {% for location in locations %}
        locations.push({ // TODO: this can surely be done better
            lat: {{ location.latitude }},
            lng: {{ location.longitude }},
            name: '{{ location.name|escapejs }}',
            description: '{{ location.description|truncatewords:60|escapejs }}',
            program: '{{ location.program|escapejs }}',
            contact: '{{ location.contact_info|escapejs }}',
            opacity: getOpacityForCredibility({{ location.credibility }}),
            url: '{{ location.get_absolute_url }}'
        });
    {% endfor %}

    var markersSetOpacity = function(ratio) {
        ratio = ratio || 1;
        for (var i in window.markers) {
            var marker = window.markers[i];
            marker.setOpacity(ratio * marker.defaultOpacity);
        }
    }

    var loadInfoWithLocation = function(location) {
        var hName = document.getElementById('hName');
        var pDescription = document.getElementById('pDescription');
        var pProgram = document.getElementById('pProgram');
        var pContact = document.getElementById('pContact');
        var aReviews = document.getElementById('aReviews');

        hName.innerHTML = location.name;
        pDescription.innerHTML = location.description;
        pProgram.innerHTML = location.program;
        pContact.innerHTML = location.contact;
        aReviews.href = location.url;
    }

    var toggleInfoVisible = function(b) {
        var locationInfo = document.getElementById('locationInfo');
        if (b === true) {
            //locationInfo.style.maxHeight = '300px';
            $('#locationInfo').collapse('show');
        }
        else {
            var aReviews = document.getElementById('aReviews');
            aReviews.href = '';
            //locationInfo.style.maxHeight = '0px';
            $('#locationInfo').collapse('hide');
        }
    }

    // Adds a marker to the map.
    var LABELS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    var labelIndex = 0;
    var addMarker = function(location, map) {
        // Add the marker at the clicked location, and add the next-available label
        // from the array of alphabetical characters.
        var marker = new google.maps.Marker({
            position: {
                lat: location.lat,
                lng: location.lng
            },
            label: LABELS[labelIndex++ % LABELS.length],
            map: map,
            defaultOpacity: location.opacity,
            opacity: location.opacity
        });

        marker.addListener('click', function() {
            loadInfoWithLocation(location);
            toggleInfoVisible(true);

            markersSetOpacity(0.5);
            this.setOpacity(1);
        });

        window.markers.push(marker);
    }

    google.maps.event.addDomListener(window, 'load', function() {
        for (var i in locations) {
            addMarker(locations[i], window.map);
        }

        window.mapElem.style.width = '100%';
        google.maps.event.trigger(map, 'resize');

        window.map.addListener('click', function() {
            toggleInfoVisible(false);
            markersSetOpacity(1);
        });
    });
</script>
{% endblock %}

templates/locations/review.html
{% extends "locations/view.html" %}
{% load i18n %}
{% load map_tags %}

{% block page_title %}
{{ location.name|title }} Review
{% endblock %}

{% block review_form %}
<form method="POST">
    {% csrf_token %}

    {% for field in review_form %}
        <div class="field-wrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}

    <input type="submit" value="{% trans "Submit" %}">
</form>
{% endblock %}

templates/locations/view.html
{% extends "base.html" %}
{% load i18n %}
{% load map_tags %}

{% block page_title %}
{{ location.name|title }}
{% if user.is_authenticated %}
    <span class="small">(<a href="{% url 'locations:edit' location.id %}">edit</a>)</span>
{% endif %}
{% endblock %}

{% block content %}
<div>
    <div class="col-xs-12 col-md-4 col-lg-4">
        <p>{% map location.latitude location.longitude True 800 400 %}</p>

        <blockquote>
            <ul>
                <li>
                    <b>Description: </b>
                    <p id="pDescription">{{ location.description }}</p>
                </li>
                <li>
                    <b>Program: </b>
                    <p id="pProgram">{{ location.program }}</p>
                </li>
                <li>
                    <b>Contact: </b>
                    <p id="pContact">{{ location.contact_info }}</p>
                </li>
                 <li>
                    <b>Credibility: </b>
                    {% widthratio location.credibility 1 100 as credibility %}
                    <p id="pCredibility">{{ credibility }}%</p>
                </li>
            </ul>
        </blockquote>
    </div>

<<<<<<< HEAD
    {% block review_form %}
    <img src="{{location.photo.url}}" alt="PhotoView" style="width:300px;height:300px"/>
    <div class="reviews">
        <h3 class="reviews__title">
            Reviews
            <span class="small">
                (<a href="{% url 'locations:review' location.id %}">Add</a>)
            </span>
        </h3>

        {% if reviews %}
        <ul class="reviews__list">
        {% for review in reviews %}
            <li>
                {{ review.content }} -
                {{ review.get_mark_display }} -
                {{ review.user.username }}
            </li>
        {% endfor %}
        </ul>
        {% else %}
        <div class="reviews__empty">
            No reviews yet
=======
    <div class="col-xs-12 col-md-8 col-lg-8">
        {% block review_form %}
        <div id="locationInfo" class="reviews panel panel-default">
            <div class="panel-heading">
                <h3 class="reviews__title">
                    Reviews
                    <span class="small">
                        (<a href="{% url 'locations:review' location.id %}">Add</a>)
                    </span>
                </h3>
            </div>
            <div class="panel-body">
                {% if reviews %}
                <ul class="reviews__list">
                {% for review in reviews %}
                    <li>
                        {{ review.content }} -
                        {{ review.get_mark_display }} -
                        {{ review.user.username }}
                    </li>
                {% endfor %}
                </ul>
                {% else %}
                <div class="reviews__empty">
                    No reviews yet
                </div>
                {% endif %}
            </div>
>>>>>>> master
        </div>
        {% endblock %}
    </div>
</div>
{% endblock %}


{% block extrajs %}
<script>
google.maps.event.addDomListener(window, 'load', function() {
    window.mapElem.style.width = '100%';
    google.maps.event.trigger(map, 'resize');
});
</script>
{% endblock %}